-- Migration 003: Add highlight_color to verses and seed topics.

-- Per-verse user highlight color (nullable — null means no highlight).
ALTER TABLE verses ADD COLUMN highlight_color TEXT DEFAULT NULL;

-- Seed topics. Insert only if the topics table is empty so re-running is safe.
INSERT INTO topics (name, color) SELECT 'Faith',            '#3B82F6' WHERE NOT EXISTS (SELECT 1 FROM topics);
INSERT INTO topics (name, color) VALUES
  ('Repentance',       '#8B5CF6'),
  ('Baptism',          '#06B6D4'),
  ('Holy Ghost',       '#F59E0B'),
  ('Atonement',        '#DC2626'),
  ('Prayer',           '#10B981'),
  ('Obedience',        '#6366F1'),
  ('Charity',          '#EC4899'),
  ('Love',             '#F43F5E'),
  ('Hope',             '#14B8A6'),
  ('Forgiveness',      '#A78BFA'),
  ('Grace',            '#D946EF'),
  ('Salvation',        '#EF4444'),
  ('Resurrection',     '#F97316'),
  ('Second Coming',    '#FBBF24'),
  ('Covenant',         '#7C3AED'),
  ('Priesthood',       '#1D4ED8'),
  ('Temple',           '#0EA5E9'),
  ('Family',           '#22C55E'),
  ('Marriage',         '#F472B6'),
  ('Service',          '#34D399'),
  ('Humility',         '#818CF8'),
  ('Gratitude',        '#FB923C'),
  ('Patience',         '#A3E635'),
  ('Wisdom',           '#2DD4BF'),
  ('Knowledge',        '#60A5FA'),
  ('Scripture Study',  '#4ADE80'),
  ('Commandments',     '#C084FC'),
  ('Agency',           '#38BDF8'),
  ('Plan of Salvation','#FB7185'),
  ('Creation',         '#4ADE80'),
  ('Fall of Adam',     '#F87171'),
  ('Judgment',         '#FACC15'),
  ('Mercy',            '#C084FC'),
  ('Justice',          '#E879F9'),
  ('Prophecy',         '#FCA5A5'),
  ('Miracles',         '#67E8F9'),
  ('Healing',          '#86EFAC'),
  ('Angels',           '#FDE68A'),
  ('Revelation',       '#DDD6FE'),
  ('Zion',             '#BAE6FD'),
  ('Tithing',          '#BBF7D0'),
  ('Fasting',          '#FBCFE8'),
  ('Word of Wisdom',   '#A7F3D0'),
  ('Missionary Work',  '#93C5FD'),
  ('Sabbath',          '#FED7AA'),
  ('Joy',              '#FDE047'),
  ('Peace',            '#99F6E4'),
  ('Adversity',        '#FCA5A5'),
  ('Jesus Christ',     '#B91C1C');
